

	/** AUTH ACTIONS */
	export const SIGN_IN_USER = 'SIGN_IN_USER'	
	export const SIGN_IN_USER_FULFILLED = 'SIGN_IN_USER_FULFILLED'
	export const SIGN_IN_USER_REJECTED='SIGN_IN_USER_REJECTED'
	export const SIGN_OUT_USER = 'SIGN_OUT_USER'
	export const SIGN_OUT_USER_FULFILLED = 'SIGN_OUT_USER_FULFILLED'
	export const SIGN_OUT_USER_REJECTED='SIGN_OUT_USER_REJECTED'
	export const AUTH_CLOSE_DISPLAY = 'AUTH_CLOSE_DISPLAY'
	
